### ISSUE TITLE
PickPivot Method

### ISSUE THREAD

**Issue by northerndiver94** [vincefox8/cs2420-05QuicksortMergesort#3]
I don't think this is correct. It should return an int so the class can use that integer to access the element T. returning the element T doesn't make sense to be because the arraylist isn't ordered by element but by index. the pivot point is only a point to swap things around based on the comparator. Does that make sense? It probably doesn't because its really late. lol
I think the header should be:
	private static int pickPivot(int n) 
because it is supposed to return the pivot point or pivot functional fraction.

**Comment by vincefox8** [comment]
I think you're right, so we first return the pivot _index_ and then use the value of the element _T_ at that index to compare. Would you mind fixing that?

**Comment by vincefox8** [comment]
Well actually on second thought I think this is right as is. The pivot returned is the _value at a certain index_ in the array as determined by the integer n, but in order to compare a pivot against the other elements we do need to return the value of the element T. 

So although the n input affects which pivot index is selected, the actual pivot itself has to be a Type of element matching the rest of the list.
